#!/usr/bin/env bash

if [ -z "$INSTANCE_KEY" ] || [ -z "$INSTANCE_ADDRESS" ]; then
    echo "INSTANCE_KEY or INSTANCE_ADDRESS variables are empty"
    exit 1
fi

if [ -z "$1" ]; then
    echo "No positional argument provided. Path expected."
    exit 1
fi

COMMAND="rsync -Pav -e 'ssh -i $INSTANCE_KEY' ./ '$INSTANCE_ADDRESS:$1'"
watchmedo shell-command --recursive --command="$COMMAND" .
